/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.CustomerWorkArea;

import business.Enterprise.Enterprise;
import business.Enterprise.GunSeller;
import business.FireArms.FireArms;
import business.Network.Network;
import business.Organization.BackGroundCheck;
import business.Organization.MaterialOrganization;
import business.Organization.Organization;
import business.Organization.SalesOrganization;
import business.SendMail.SendMail;
import business.UserAccount.UserAccount;
import business.WorkQueue.SalesWorkRequest;
import business.WorkQueue.WorkQueue;
import java.awt.CardLayout;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dhwani
 */
public class CustomerWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form CustomerWorkArea
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private Network network;
    private Organization orgBkgdck = null;
    public CustomerWorkArea(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        this.network = network;
        populateTable();   
    }
    public void populateTable(){
    DefaultTableModel dtm = (DefaultTableModel)tblItemDet.getModel();
    dtm.setRowCount(0);
    for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
    if(enterprise instanceof GunSeller){
    for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
    if(org instanceof MaterialOrganization){
    for(FireArms fa : org.getFireArmsDirectory().getFireArmsList()){
    Object[] row = new Object[6];
    row[0] = enterprise;
    row[1] = fa.getGunType();
    row[2] = fa;
    row[3] = fa.getSku();
    row[4] = fa.getPrice();
    row[5] = fa.getQuantity()>0?"In Stock":"Out of Stock";
    dtm.addRow(row);
    }
    }
    }
    }
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblItemDet = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtGunType = new javax.swing.JTextField();
        txtGunSeller = new javax.swing.JTextField();

        setBackground(new java.awt.Color(19, 115, 163));

        tblItemDet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Gun Seller", "Gun Type", "Model", "SKU", "Price", "Availability"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblItemDet);

        btnSearch.setBackground(new java.awt.Color(0, 153, 153));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(0, 153, 153));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnBook.setBackground(new java.awt.Color(0, 153, 153));
        btnBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBook.setForeground(new java.awt.Color(255, 255, 255));
        btnBook.setText("Select and Place Order");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Check Order(s) >>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Gun Seller");

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Gun Type");

        txtGunType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGunTypeActionPerformed(evt);
            }
        });

        txtGunSeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGunSellerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBook))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtGunType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtGunSeller, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(87, 87, 87)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtGunSeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGunType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSearch)
                        .addComponent(btnReset))
                    .addComponent(btnBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    DefaultTableModel dtm = (DefaultTableModel)tblItemDet.getModel();
    if(!txtGunSeller.getText().isEmpty() && !txtGunType.getText().isEmpty()){
    for(int row = 0; row < dtm.getRowCount(); row++){
    Enterprise enterprise = (Enterprise)tblItemDet.getValueAt(row, 0);
    FireArms fa = (FireArms)tblItemDet.getValueAt(row, 2);
    if(!enterprise.getName().equalsIgnoreCase(txtGunSeller.getText()) && 
       !fa.getGunType().equalsIgnoreCase(txtGunType.getText())){
    dtm.removeRow(row);
    row--;
    }
    }
    }else if(!txtGunSeller.getText().isEmpty() && txtGunType.getText().isEmpty()){
    for(int row = 0; row < dtm.getRowCount(); row++){
    Enterprise enterprise = (Enterprise)tblItemDet.getValueAt(row, 0);
    if(!enterprise.getName().equalsIgnoreCase(txtGunSeller.getText())){
    dtm.removeRow(row);
    row--;
    }}
    }else if(txtGunSeller.getText().isEmpty() && !txtGunType.getText().isEmpty()){
    for(int row = 0; row < dtm.getRowCount(); row++){
    FireArms fa = (FireArms)tblItemDet.getValueAt(row, 2);
    if(!fa.getGunType().equalsIgnoreCase(txtGunType.getText())){
    dtm.removeRow(row);
    row--;
    }}
    }      
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
    populateTable();
    txtGunSeller.setText("");
    txtGunType.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblItemDet.getSelectedRow();
        if(selectedRow>=0){
        Organization orgSales = null;
        Random random = new Random();
        int no = random.nextInt(5000) + 1;
        FireArms fireArms = (FireArms)tblItemDet.getValueAt(selectedRow, 2);
        for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
        for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
        if(organization instanceof SalesOrganization){
            orgSales = organization;
        }else if(organization instanceof BackGroundCheck){
        orgBkgdck = organization;
        }
            
        }}
        SalesWorkRequest request = new SalesWorkRequest();
        request.setNo(no);
        request.setFireArms(fireArms);
        request.setSender(account);
        request.setStatus("Under Process");
        request.setMessage("Pending with police for background verification");
        orgSales.getWorkQueue().getWorkRequest().add(request);
        account.getWorkQueue().getWorkRequest().add(request);
        orgBkgdck.getWorkQueue().getWorkRequest().add(request);
        JOptionPane.showMessageDialog(null, "Order placed successfully!" + "\n" + "Please complete the risk assessment.");
        SendMail.send("shah.dhw@husky.neu.edu", "We've received your order #" + no, 
        "Hi "+account.getCustomer().getfName()+","+'\n'+'\n'+
         "Thank you for shopping with us."+"\n"+'\n'+"You Ordered "+fireArms.getGunType() 
                + " " + fireArms.getModel() + " " + fireArms.getPrice()+
                '\n'+'\n'+"Please complete the risk assessment."
                , "dhwanishah781@gmail.com", "9769402842");
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Select any Row");
        }
    }//GEN-LAST:event_btnBookActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    ViewOrders panel = new ViewOrders(userProcessContainer, account, orgBkgdck);
    userProcessContainer.add("ViewOrders",panel);
    CardLayout layout = (CardLayout)userProcessContainer.getLayout();
    layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtGunSellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGunSellerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGunSellerActionPerformed

    private void txtGunTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGunTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGunTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblItemDet;
    private javax.swing.JTextField txtGunSeller;
    private javax.swing.JTextField txtGunType;
    // End of variables declaration//GEN-END:variables
}
