/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.GunLicense;

import business.EcoSystem;
import business.Organization.GunLicenseOrganization;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Dhwani Shah
 */
public class GunLicenseWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form GunLicenseWorkArea
     */
    private JPanel userProcessContainer; 
    private UserAccount account; 
    private EcoSystem business;
    private Organization organization;
    public GunLicenseWorkArea(JPanel userProcessContainer, UserAccount account, Organization organization,
            EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = business;
        this.organization = (GunLicenseOrganization)organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOpenRq = new javax.swing.JButton();
        btnClosedRq = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(19, 115, 163));

        btnOpenRq.setBackground(new java.awt.Color(0, 153, 153));
        btnOpenRq.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOpenRq.setForeground(new java.awt.Color(255, 255, 255));
        btnOpenRq.setText("Open Request(s)");
        btnOpenRq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenRqActionPerformed(evt);
            }
        });

        btnClosedRq.setBackground(new java.awt.Color(0, 153, 153));
        btnClosedRq.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClosedRq.setForeground(new java.awt.Color(255, 255, 255));
        btnClosedRq.setText("Closed Request(s)");
        btnClosedRq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClosedRqActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Gun License");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnClosedRq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenRq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(btnOpenRq)
                .addGap(18, 18, 18)
                .addComponent(btnClosedRq)
                .addContainerGap(166, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenRqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenRqActionPerformed
     GunLicenseOpenRequest panel = new GunLicenseOpenRequest(userProcessContainer, account, organization, business);
     userProcessContainer.add("GunLicenseOpenRequest",panel);
     CardLayout layout = (CardLayout)userProcessContainer.getLayout();
     layout.next(userProcessContainer);
    }//GEN-LAST:event_btnOpenRqActionPerformed

    private void btnClosedRqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClosedRqActionPerformed
     GunLicenseClosedRequest panel = new GunLicenseClosedRequest(userProcessContainer, account, organization, business);
     userProcessContainer.add("GunLicenseClosedRequest",panel);
     CardLayout layout = (CardLayout)userProcessContainer.getLayout();
     layout.next(userProcessContainer);
    }//GEN-LAST:event_btnClosedRqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClosedRq;
    private javax.swing.JButton btnOpenRq;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
