/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.BackGroundCheck;

import business.Criminal.Criminal;
import business.EcoSystem;
import business.GunLicense.GunLicense;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Dhwani
 */
public class ViewStatsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewStatsJPanel
     */
    private JPanel userProcessContainer; 
    private WorkRequest workrq;
    private EcoSystem business;
    ViewStatsJPanel(JPanel userProcessContainer, WorkRequest workrq, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.workrq = workrq;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGunViolence = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnGunOwners = new javax.swing.JButton();
        btnWeapons = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(19, 115, 163));

        btnGunViolence.setBackground(new java.awt.Color(0, 153, 153));
        btnGunViolence.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGunViolence.setForeground(new java.awt.Color(255, 255, 255));
        btnGunViolence.setText("No of Gun Violence Reported");
        btnGunViolence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGunViolenceActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnGunOwners.setBackground(new java.awt.Color(0, 153, 153));
        btnGunOwners.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGunOwners.setForeground(new java.awt.Color(255, 255, 255));
        btnGunOwners.setText("Number of Gun Owners");
        btnGunOwners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGunOwnersActionPerformed(evt);
            }
        });

        btnWeapons.setBackground(new java.awt.Color(0, 153, 153));
        btnWeapons.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnWeapons.setForeground(new java.awt.Color(255, 255, 255));
        btnWeapons.setText("Weapons used for Violence");
        btnWeapons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWeaponsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Statistics");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGunViolence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGunOwners, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnWeapons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addComponent(btnGunViolence)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGunOwners)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnWeapons)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGunViolenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGunViolenceActionPerformed
    ArrayList<String> yearList = new ArrayList<>();
    DefaultCategoryDataset dcd = new DefaultCategoryDataset();
    int counter;
    for(Criminal criminal : business.getCriminalDirectory().getCriminalList()){
    if(!yearList.contains(criminal.getYear())){
    yearList.add(String.valueOf(criminal.getYear()));
    }
    }
    for(String yr : yearList){
    counter = 0;
    for(Criminal criminal : business.getCriminalDirectory().getCriminalList()){
    if(yr.equalsIgnoreCase(String.valueOf(criminal.getYear())) && 
            criminal.getCrimeType().equalsIgnoreCase("Gun Violence")){
    counter = counter + 1;
    }
    }
    dcd.setValue(counter, "NoOfGunViolence", yr);
    }
    JFreeChart chart = ChartFactory.createBarChart("Gun Violence Reported in area " + workrq.getSender().getCustomer().getZip(), 
            "Year", "No of Gun Violence", dcd, PlotOrientation.VERTICAL, false, true, false);
    CategoryPlot p = chart.getCategoryPlot();
    p.setRangeGridlinePaint(Color.black);
    ChartFrame frame = new ChartFrame("Bar Chart", chart);
    frame.setVisible(true);
    frame.setSize(450,350);
    }//GEN-LAST:event_btnGunViolenceActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    userProcessContainer.remove(this);
    CardLayout layout = (CardLayout)userProcessContainer.getLayout();
    layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnGunOwnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGunOwnersActionPerformed
        ArrayList<String> yearList = new ArrayList<>();
        DefaultCategoryDataset dcd = new DefaultCategoryDataset();
        int counter;
        for(GunLicense gl : business.getGunLicenseDirectory().getGunLicenseList()){
            System.out.println(gl.getValidFrom().substring(23, 28));
            if(!yearList.contains(gl.getValidFrom().substring(23, 28)) &&
                workrq.getSender().getCustomer().getZip()==gl.getOwner().getZip()){
                yearList.add(String.valueOf(gl.getValidFrom().substring(23, 28)));
            }
        }
        for(String yr : yearList){
            counter = 0;
            for(GunLicense gl : business.getGunLicenseDirectory().getGunLicenseList()){
                if(yr.equalsIgnoreCase(String.valueOf(gl.getValidFrom().substring(23, 28)))
                    && workrq.getSender().getCustomer().getZip()==gl.getOwner().getZip()){
                    counter = counter + 1;
                }
            }
            dcd.setValue(counter, "NoOfGunOwner(s)", yr);
        }
        JFreeChart chart = ChartFactory.createBarChart("Gun Owner(s) in area " + workrq.getSender().getCustomer().getZip(),
            "Year", "No of Gun Owner(s)", dcd, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        ChartFrame frame = new ChartFrame("Bar Chart", chart);
        frame.setVisible(true);
        frame.setSize(450,350);
    }//GEN-LAST:event_btnGunOwnersActionPerformed

    private void btnWeaponsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWeaponsActionPerformed
        ArrayList<String> weaponsList = new ArrayList<>();
        DefaultCategoryDataset dcd = new DefaultCategoryDataset();
        int counter;
        for(Criminal criminal : business.getCriminalDirectory().getCriminalList()){
            if(!weaponsList.contains(criminal.getWeaponUsed()) &&
                workrq.getSender().getCustomer().getZip()==criminal.getZip()){
                weaponsList.add(criminal.getWeaponUsed());
            }
        }
        for(String weapon : weaponsList){
            counter = 0;
            for(Criminal criminal : business.getCriminalDirectory().getCriminalList()){
                if(weapon.equalsIgnoreCase(criminal.getWeaponUsed()) &&
                    criminal.getCrimeType().equalsIgnoreCase("Gun Violence")
                    && workrq.getSender().getCustomer().getZip()==criminal.getZip()){
                    counter = counter + 1;
                }
            }
            dcd.setValue(counter, "NoOfTimes", weapon);
        }
        JFreeChart chart = ChartFactory.createBarChart("Weapons used for Violence in area " + workrq.getSender().getCustomer().getZip(),
            "Weapons", "No of Times", dcd, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        ChartFrame frame = new ChartFrame("Bar Chart", chart);
        frame.setVisible(true);
        frame.setSize(450,350);
    }//GEN-LAST:event_btnWeaponsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGunOwners;
    private javax.swing.JButton btnGunViolence;
    private javax.swing.JButton btnWeapons;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
