/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.MentalHealthCheckUp;

import business.Appointment.Appointment;
import business.SendMail.SendMail;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.SpinnerDateModel;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Dhwani
 */
public class ScheduleAppointmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ScheduleAppointmentJPanel
     */
    private JPanel userProcessContainer;
    private WorkRequest wr;
    ScheduleAppointmentJPanel(JPanel userProcessContainer, WorkRequest wr) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.wr = wr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDoctor = new javax.swing.JComboBox<>();
        Date date = new Date();
        SpinnerDateModel sm = new SpinnerDateModel(date, null, null,
            java.util.Calendar.HOUR_OF_DAY);
        txtTime = new javax.swing.JSpinner(sm);
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDate = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(19, 115, 163));

        txtDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr John", "Dr Sachin" }));

        javax.swing.JSpinner.DateEditor de = new javax.swing.JSpinner.DateEditor(txtTime, "HH:mm:ss");
        txtTime.setEditor(de);

        btnSave.setBackground(new java.awt.Color(0, 153, 153));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Schedule Appointment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btnSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    if(txtDate.getDate()==null || txtTime.getValue()==null){
            JOptionPane.showMessageDialog(null, "Please fill in all the fields.",
        "Error", JOptionPane.ERROR_MESSAGE);
    }else{
    Appointment app = new Appointment();
    app.setDoctor(txtDoctor.getItemAt(txtDoctor.getSelectedIndex()));
    app.setDate(String.valueOf(txtDate.getDate()));
    app.setTime(String.valueOf(txtTime.getValue()));
    wr.setStatus("Appointment Scheduled");
    wr.getAppointmentDirectory().getAppointmentList().add(app);
                JOptionPane.showMessageDialog(null, "Appointment Scheduled!");
       txtDoctor.setEnabled(false);txtDate.setEnabled(false);txtTime.setEnabled(false);
       SendMail.send("shah.dhw@husky.neu.edu", "Appointment Confirmation","Hi " 
       +wr.getSender().getCustomer().getfName()+","+'\n'+'\n'
       +"Greetings"+'\n'+'\n'+"This is a friendly reminder about your mental health examination"
       +'\n'+'\n'+"Appointment Information"+'\n'+txtDoctor.getItemAt(txtDoctor.getSelectedIndex())
       +'\n'+txtDate.getDate()+'\n'+'\n'+
       "We look forward to seeing you at your appointment."
               ,"dhwanishah781@gmail.com", "9769402842");
     userProcessContainer.remove(this);
     Component[] componentArray = userProcessContainer.getComponents();
     Component component = componentArray[componentArray.length - 1];
     MhcpOpenRequest mhcp = (MhcpOpenRequest)component;
     mhcp.populateTable();
     CardLayout layout = (CardLayout)userProcessContainer.getLayout();
     layout.previous(userProcessContainer);  
    }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
     userProcessContainer.remove(this);
     Component[] componentArray = userProcessContainer.getComponents();
     Component component = componentArray[componentArray.length - 1];
     MhcpOpenRequest mhcp = (MhcpOpenRequest)component;
     mhcp.populateTable();
     CardLayout layout = (CardLayout)userProcessContainer.getLayout();
     layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JComboBox<String> txtDoctor;
    private javax.swing.JSpinner txtTime;
    // End of variables declaration//GEN-END:variables
}
